### ISSUE TITLE
Fix ZeroDivisionError on freebox/sensor 

### ISSUE THREAD

**Issue by davelowper** [hacf-fr/home-assistant-core#88]
### The problem

Freebox Delta is reporting a total size of zero on main hard drive (bug!!)
![image](https://user-images.githubusercontent.com/9915894/135925516-f0b09e44-e15a-489c-9e12-732990f929c4.png)

This causes in turn a ZeroDivisionError on sensor.
`Traceback (most recent call last):
  File "/workspaces/hacf/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/workspaces/hacf/homeassistant/helpers/entity_platform.py", line 587, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/workspaces/hacf/homeassistant/helpers/entity.py", line 698, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/workspaces/hacf/homeassistant/components/freebox/sensor.py", line 149, in async_added_to_hass
    self.async_update_state()
  File "/workspaces/hacf/homeassistant/components/freebox/sensor.py", line 227, in async_update_state
    self._partition["free_bytes"] * 100 / self._partition["total_bytes"], 2
ZeroDivisionError: division by zero`

### What is version of Home Assistant Core has the issue?

core-2021.9.0.dev0

### What type of installation are you running?

Home Assistant Container

### Integration causing the issue

freebox

**Comment by oncleben31** [comment]
Thanks for reporting it. Even if it make sens to put it here you should start by opening an issue on the [official repo](https://github.com/home-assistant/core).

**Comment by oncleben31** [comment]
Topic discussed on official reports: https://github.com/home-assistant/core/pull/57077
